apiVersion: kafka.lrolaz.io/v1alpha1
kind: KafkaTopic
metadata:
  name: example07
  namespace: kube-public
spec:
  topicName: example07
  partitions: 1
  replicas: 1
  config:
    compression.type: "producer"
    cleanup.policy: "delete"
    retention.ms: "604800000"
    max.message.bytes: "10485"
    retention.bytes: "-1"