---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-token
  namespace: kube-kafka
data:
  token: MDkxOWFlZjktYjEwOC0zZGU2LTEzMGMtMjk0YmNhM2Q2YTUw    
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: vault-kafka-issuer
  namespace: kube-kafka
spec:
  vault:
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token
        key: token
    path: PictetRoboCA1/issue/kube-kafka
    server: https://vault.kube-security.svc.cluster.local:8200
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: vault-issuer
  commonName: example.com
  dnsNames:
  - www.example.com
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: my-certificate2
  namespace: kube-security
spec:
  secretName: my-certificate-secret
  commonName: example.com
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer    