---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
rules:
- apiGroups:
  - "kafka.lrolaz.io"
  resources:
  - kafkatopics
  - kafkausers
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups: ["certmanager.k8s.io"]
  resources: ["certificates"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: kafka-strimzi-topic-operator
    namespace: kube-kafka
roleRef:
  kind: ClusterRole
  name: kafka-strimzi-topic-operator
  apiGroup: rbac.authorization.k8s.io

---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/crd.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.lrolaz.io
spec:
  group: kafka.lrolaz.io
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            partitions:
              type: integer
              minimum: 1
            replicas:
              type: integer
              minimum: 1
              maximum: 32767
            config:
              type: object
            topicName:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.lrolaz.io
spec:
  group: kafka.lrolaz.io
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    plural: kafkausers
    singular: kafkauser
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            authentication:
              type: object
              properties:
                tls:
                  type: object
                  properties: 
                    secretName:
                      type: string
                    issuerName:
                      type: string
                    issuerKind:
                      type: string                                     
            
---  
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kafka-topic-operator-certificate
  namespace: kube-kafka
spec:
  secretName: kafka-topic-operator-certificate
  commonName: kafka-topic-operator
  issuerRef:
    name: vault-kafka-issuer
    kind: Issuer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
spec:
  replicas: 
  selector:
    matchLabels:
      app: strimzi-topic-operator
      release: kafka
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: strimzi-topic-operator
        release: kafka      
    spec:
      securityContext:
        runAsUser: 999   
      serviceAccountName: kafka-strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          image: "eu.gcr.io/kube-kafka-labo/kafka-topic-operator:latest"
          command:
          - kafka-topic-operator
          imagePullPolicy: Always          
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-cp-kafka-headless.kube-kafka.svc.cluster.local:9093
            - name: OPERATOR_TLS_CERT_FILE
              value: /etc/kafka/secrets/cert/tls.crt            
            - name: OPERATOR_TLS_KEY_FILE
              value: /etc/kafka/secrets/cert/tls.key          
            - name: OPERATOR_TLS_CA_FILE
              value: /etc/kafka/secrets/ca/tls.crt
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
          volumeMounts:  
            - name: tls-ca
              mountPath: /etc/kafka/secrets/ca               
            - name: tls-cert
              mountPath: /etc/kafka/secrets/cert  
      volumes:
      - name: tls-ca
        secret:
          secretName: ca             
      - name: tls-cert
        secret:
          secretName: kafka-topic-operator-certificate
