apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: example02
  namespace: kube-public
  labels:
    strimzi.io/kind: topic  
spec:
  partitions: 1
  replicas: 2
  config:
    compression.type: producer
    cleanup.policy: delete
    retention.ms: 604800000
    max.message.bytes: 1048576
    retention.bytes: -1
---
apiVersion: v1
kind: Pod
metadata:
  name: example-consumer
  namespace: kube-public
spec:
      initContainers:
        - name: certificate-init-container
          image: lrolaz/certificate-init-container:0.0.18
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP                  
          args:
            - "-issuer-name=vault-kafka-issuer"
            - "-issuer-kind=Issuer"          
            - "-secret-name=$(POD_NAME)-certificate"
            - "-namespace=$(NAMESPACE)"
            - "-pod-ip=$(POD_IP)"
            - "-pod-name=$(POD_NAME)"
            - "-service-ips=$(HOST_IP)"
            - "-service-names=kafka-cp-kafka-headless"                             
            - "-keystore-secret-name=kafka-cp-kafka-keystores" 
  containers:
  - name: example-consumer
    image: strimzi/kafka:latest
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["bin/kafka-console-consumer.sh"]
    args: ["--bootstrap-server", "kafka-cp-kafka-headless.kube-kafka.svc.cluster.local:9092", "--topic", "example02", "--from-beginning", "--group", "example-consumer01"]  
---
apiVersion: v1
kind: Pod
metadata:
  name: example-producer
  namespace: kube-public
spec:
  containers:
  - name: example-producer
    image: strimzi/kafka:latest
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["bin/kafka-producer-perf-test.sh"]
    args: ["--producer-props", "bootstrap.servers=kafka-cp-kafka.kube-kafka.svc.cluster.local:9092", "--topic", "example02", "--num-records", "100000", "--throughput", "10", "--record-size", "10"]   
  restartPolicy: Never  