---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-strimzi-user-operator
  namespace: kube-kafka
  labels:
    app: strimzi-user-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kafka-strimzi-user-operator
  namespace: kube-kafka
  labels:
    app: strimzi-user-operator
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - kafkausers
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kafka-strimzi-user-operator
  namespace: kube-kafka
  labels:
    app: strimzi-user-operator
subjects:
  - kind: ServiceAccount
    name: kafka-strimzi-user-operator
    namespace: kube-kafka
roleRef:
  kind: ClusterRole
  name: kafka-strimzi-user-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.strimzi.io
  labels:
    app: strimzi-user-operator
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    singular: kafkauser
    plural: kafkausers
    shortNames:
    - ku
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            authentication:
              type: object
              properties:
                type:
                  type: string
                  enum:
                  - tls
                  - scram-sha-512
              required:
              - type
            authorization:
              type: object
              properties:
                acls:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      operation:
                        type: string
                        enum:
                        - Read
                        - Write
                        - Create
                        - Delete
                        - Alter
                        - Describe
                        - ClusterAction
                        - AlterConfigs
                        - DescribeConfigs
                        - IdempotentWrite
                        - All
                      resource:
                        type: object
                        properties:
                          name:
                            type: string
                          patternType:
                            type: string
                            enum:
                            - literal
                            - prefix
                          type:
                            type: string
                            enum:
                            - topic
                            - group
                            - cluster
                        required:
                        - type
                      type:
                        type: string
                        enum:
                        - allow
                        - deny
                    required:
                    - operation
                    - resource
                type:
                  type: string
                  enum:
                  - simple
              required:
              - acls
              - type
          required:
          - authentication
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-user-operator
  namespace: kube-kafka  
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-user-operator
    spec:
      serviceAccountName: kafka-strimzi-user-operator
      containers:
        - name: strimzi-user-operator
          image: strimzi/user-operator:latest
          env:
            - name: STRIMZI_NAMESPACE
              value: kube-public
            - name: STRIMZI_LABELS
              value: "strimzi.io/kind=user"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: kafka-cp-zookeeper-headless:2181
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "20000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_CA_CERT_NAME
              value: kafka-cp-kafka-keystores
            - name: STRIMZI_CA_KEY_NAME
              value: dummy
          resources:
            limits:
              memory: 256Mi
              cpu: 100m
            requests:
              memory: 256Mi
              cpu: 100m
  strategy:
    type: Recreate
