---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
rules:
- apiGroups:
  - "kafka.strimzi.io"
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: kafka-strimzi-topic-operator
    namespace: kube-kafka
roleRef:
  kind: ClusterRole
  name: kafka-strimzi-topic-operator
  apiGroup: rbac.authorization.k8s.io

---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/crd.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.strimzi.io
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    singular: kafkatopic
    plural: kafkatopics
    shortNames:
    - kt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            partitions:
              type: integer
              minimum: 1
            replicas:
              type: integer
              minimum: 1
              maximum: 32767
            config:
              type: object
            topicName:
              type: string
---
# Source: cp-helm-charts/charts/strimzi-topic-operator/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kafka-strimzi-topic-operator
  namespace: kube-kafka
  labels:
    app: strimzi-topic-operator
    chart: strimzi-topic-operator-0.1.0
    release: kafka
    heritage: Tiller
spec:
  replicas: 
  selector:
    matchLabels:
      app: strimzi-topic-operator
      release: kafka
  template:
    metadata:
      labels:
        app: strimzi-topic-operator
        release: kafka      
    spec:
      securityContext:
        runAsUser: 999   
      serviceAccountName: kafka-strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          image: "strimzi/topic-operator:latest"
          env:
            - name: STRIMZI_CONFIGMAP_LABELS
              value: "strimzi.io/kind=topic"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-cp-kafka-headless:9092
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: kafka-cp-zookeeper-headless:2181
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "20000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "360000"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_NAMESPACE
              value: kube-public
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
  strategy:
    type: Recreate
