apiVersion: v1
kind: Service
metadata:
  name: vault-load-balancer
spec:
  type: LoadBalancer
  loadBalancerIP: 35.240.0.186
  ports:
    - name: http
      port: 8200
    - name: server
      port: 8201
  selector:
    app: vault
